RsseRazorPages/Pages/AddText.cshtml.cs
using Microsoft.Extensions.Logging;
using RandomSongSearchEngine.Classes;
using System;
using System.Threading.Tasks;
using RandomSongSearchEngine.DBContext;
using Microsoft.Extensions.DependencyInjection;

namespace RandomSongSearchEngine.Pages
{
    /// <summary>
    /// Добавление новой песни
    /// </summary>
    public class AddTextModel : BasePageModel
    {
        private readonly ILogger<AddTextModel> _logger;

        //public AddTextModel(RazorDbContext injectedContext, ILogger<AddTextModel> logger) : base(injectedContext)
        public AddTextModel(IServiceScopeFactory serviceScopeFactory, ILogger<AddTextModel> logger) : base(serviceScopeFactory)
        {
            _logger = logger;
        }

        public async Task OnGetAsync()
        {
            try
            {
                //await using (var database = new RazorDbContext())
                using (var scope = _serviceScopeFactory.CreateScope())//
                {
                    var database = scope.ServiceProvider.GetRequiredService<DatabaseContext>();//
                    
                    await CreateCheckboxesNamesAsync(database);
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e, "[AddTextModel]");
            }
        }

        public async Task OnPostAsync()
        {
            if (AreChecked.Count == 0 || TextFromHtml == null || TitleFromHtml == null)
            {
                await OnGetAsync();
                return;
            }
            try
            {
                //await using (var database = new RazorDbContext())
                using (var scope = _serviceScopeFactory.CreateScope())//
                {
                    var database = scope.ServiceProvider.GetRequiredService<DatabaseContext>();//
                    
                    await AddSongToDatabaseAsync(database);
                    await CreateTextAndTitleAsync(database, SavedTextId);
                }
                await OnGetAsync();//
                InitCheckedGenres();
            }
            catch (Exception e)
            {
                _logger.LogError(e, "[AddTextModel]");
                await OnGetAsync();//
            }
        }
    }
}

RsseRazorPages/Pages/Catalog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using RandomSongSearchEngine.Classes;
using RandomSongSearchEngine.DBContext;

namespace RandomSongSearchEngine.Pages
{
    /// <summary>
    /// Каталог песен
    /// </summary>
    public class CatalogModel : BasePageModel
    {
        private readonly ILogger<CatalogModel> _logger;

        /// <summary>
        /// Количество песен на одной странице
        /// </summary>
        private readonly int pageSize;

        public CatalogModel(IServiceScopeFactory serviceScopeFactory, ILogger<CatalogModel> logger) : base(serviceScopeFactory)
        {
            _logger = logger;
            pageSize = 15;
            try
            {
                using (var scope = _serviceScopeFactory.CreateScope())//
                {
                    var database = scope.ServiceProvider.GetRequiredService<DatabaseContext>();//
                    SongsCount = database.Text.Count();
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e, "[CatalogModel]: no database");
                //в случае отсутствия бд мы не придём к null referenece exception из-за TitleAndTextID
                TitleAndTextID = new List<Tuple<string, int>>();
            }
        }

        /// <summary>
        /// Используется для определения какая кнопка была нажата во вьюхе
        /// </summary>
        [BindProperty]
        public List<int> NavigationButtons { get; set; }

        /// <summary>
        /// Количество песен в базе данных
        /// </summary>
        [BindProperty]
        public int SongsCount { get; set; }

        /// <summary>
        /// Номер последней просмотренной страницы
        /// </summary>
        public int PageNumber { get; set; }

        public async Task OnGetAsync(int id)
        {
            PageNumber = id;
            try
            {
                using (var scope = _serviceScopeFactory.CreateScope())//
                {
                    var database = scope.ServiceProvider.GetRequiredService<DatabaseContext>();//
                    await CreateSongsDataCatalogViewAsync(database, PageNumber, pageSize);
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e, "[CatalogModel]");
            }
        }

        /// <summary>
        /// Переход на страницу редактирования песни при клике на неё ("ChangeText")
        /// </summary>
        /// <param name="id">ID песни</param>
        /// <returns></returns>
        public IActionResult OnGetRedirect(int id)
        {
            SavedTextId = id;
            return RedirectToPage("ChangeText", new { id });
        }

        public async Task OnPostAsync(int id)
        {
            //Предполагается, что браузер прислал неиспорченные данные
            PageNumber = id;
            if (NavigationButtons != null && NavigationButtons[0] == 2)
            {
                //double r = Math.Ceiling(SongsCount / (double)pageSize);
                int pageCount = Math.DivRem(SongsCount, pageSize, out int remainder);
                if (remainder > 0)
                {
                    pageCount++;
                }
                if (PageNumber < pageCount)
                {
                    PageNumber++;
                }
            }
            if (NavigationButtons != null && NavigationButtons[0] == 1)
            {
                if (PageNumber > 1)
                {
                    PageNumber--;
                }
            }
            await OnGetAsync(PageNumber);
        }
    }
}

RsseRazorPages/Pages/ChangeText.cshtml.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using RandomSongSearchEngine.Classes;
using RandomSongSearchEngine.DBContext;

namespace RandomSongSearchEngine.Pages
{
    /// <summary>
    /// Изменение существующей песни
    /// </summary>
    public class ChangeTextModel : BasePageModel
    {
        private readonly ILogger<ChangeTextModel> _logger;

        public ChangeTextModel(IServiceScopeFactory serviceScopeFactory, ILogger<ChangeTextModel> logger) : base(serviceScopeFactory)
        {
            _logger = logger;
        }

        /// <summary>
        /// Сериализованный список категорий и Id песни
        /// </summary>
        [BindProperty]
        public string InitialCheckboxesAndTextId { get; set; }

        /// <summary>
        /// Список категорий в первоначальном варианте песни
        /// </summary>
        private List<int> InitialCheckboxes { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            SavedTextId = id;
            try
            {
                if (SavedTextId == 0)
                {
                    return RedirectToPage("AddText");
                }
                using (var scope = _serviceScopeFactory.CreateScope())
                {
                    var database = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
                    await CreateTextAndTitleAsync(database, SavedTextId);
                    await CreateCheckboxesNamesAsync(database);
                    InitialCheckboxes = await CreateCheckedGenresAsync(database);
                    SerializeForView(InitialCheckboxes);
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e, "[ChangeTextModel]");
            }
            return Page();
        }

        public async Task OnPostAsync(string checkboxes)
        {
            InitialCheckboxes = DeserializeFromView(checkboxes);
            try
            {
                if (AreChecked.Count == 0 || TextFromHtml == null || TitleFromHtml == null)
                {
                    await OnGetAsync(SavedTextId);
                    return;
                }

                using (var scope = _serviceScopeFactory.CreateScope())
                {
                    var database = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
                    await ChangeSongInDatabaseAsync(database, InitialCheckboxes);
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e, "[ChangeTextModel]");
            }
            await OnGetAsync(SavedTextId);
        }

        /// <summary>
        /// Десериализация в список категорий (и Id песни)
        /// </summary>
        /// <param name="s">Строка с сериализованными данными</param>
        /// <returns>Список категорий</returns>
        private List<int> DeserializeFromView(string s)
        {
            //Предполагается, что браузер прислал неиспорченные данные
            List<int> ints = new List<int>();
            string[] strings = s.Split(" ");
            foreach (var oneNumber in strings)
            {
                ints.Add(int.Parse(oneNumber));
            }
            SavedTextId = ints[ints.Count - 1];//[^1]
            ints.RemoveAt(ints.Count - 1);//[^1]
            return ints;
        }

        /// <summary>
        /// Сериализация из списка категорий (и Id песни)
        /// </summary>
        /// <param name="checkboxes">Список категорий</param>
        private void SerializeForView(List<int> checkboxes)
        {
            StringBuilder s = new StringBuilder();
            foreach (var i in checkboxes)
            {
                s.Append(i.ToString() + " ");
            }
            s.Append(SavedTextId.ToString());//
            InitialCheckboxesAndTextId = s.ToString().Trim();
        }

        /// <summary>
        /// Формируется список жанров, к которым принадлежит песня
        /// </summary>
        /// <param name="database">Контекст базы данных</param>
        /// <returns>Список жанров</returns>
        private async Task<List<int>> CreateCheckedGenresAsync(DatabaseContext database)
        {
            List<int> checkedList = await database.CreateCheckedListChangeViewSql(SavedTextId).ToListAsync();
            foreach (int i in checkedList)
            {
                GenresChecked[i - 1] = "checked";
            }
            return checkedList;
        }
    }
}

RsseRazorPages/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using RandomSongSearchEngine.Classes;

namespace RandomSongSearchEngine.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : BasePageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        //public ErrorModel(RazorDbContext injectedContext, ILogger<ErrorModel> logger) : base(injectedContext)
        public ErrorModel(IServiceScopeFactory serviceScopeFactory, ILogger<ErrorModel> logger) : base(serviceScopeFactory)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RsseRazorPages/Pages/Index.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using RandomSongSearchEngine.Classes;
using RandomSongSearchEngine.DBContext;

namespace RandomSongSearchEngine.Pages
{
    //TODO убери js из layout
    //TODO при каждом создании BasePageModel происходит injected context контекста Pasha который не уничтожается - может это и жрёт память? (нет)
    //TODO разберись с transparent
    //TODO удаляй каменты
    //TODO вынеси цсс из layout
    //TODO удали (?) error, validationScript, viewImoprt, viewStart
    //TODO appsettings.json "Microsoft": "Warning" instead of "Information"
    //TODO ставь решарпер и асинк-плагин: get brains (см. stepik) до 7 ноября
    //1. поля (статика сверху) - конструктор - свойства - методы
    //2. паблик-протектед-приват (свойства и методы)
    //3. документация на паблик и протектед

    //NEW TODO
    //catalog Math.DivRem()
    /// <summary>
    /// Вывод случайной песни по выбранным категориям
    /// </summary>
    public class IndexModel : BasePageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(IServiceScopeFactory serviceScopeFactory, ILogger<IndexModel> logger) : base(serviceScopeFactory)
        {
            _logger = logger;
        }

        public async Task OnGetAsync()
        {
            //_logger.LogId(this);
            try
            {
                using (var scope = _serviceScopeFactory.CreateScope())
                {
                    var database = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
                    await CreateCheckboxesNamesAsync(database: database);
                }
                InitCheckedGenres();
            }
            catch (Exception e)
            {
                _logger.LogError(e, "[IndexModel: OnGet Error]");
            }
        }

        public async Task OnPostAsync()
        {
            try
            {
                await GetRandomSongAsync();
                await OnGetAsync();
            }
            catch (Exception e)
            {
                _logger.LogError(e, "[IndexModel: OnPost Error]");
            }
        }

        /// <summary>
        /// Выбирает из базы данных случайную песню, относящуюся к заданным категориям
        /// </summary>
        private async Task GetRandomSongAsync()
        {
            if (AreChecked.Count == 0)
            {
                return;
            }
            using (var scope = _serviceScopeFactory.CreateScope())
            {
                var database = scope.ServiceProvider.GetRequiredService<DatabaseContext>();
                int randomResult = await database.RandomizatorAsync(AreChecked);
                if (randomResult == 0)
                {
                    return;
                }
                await CreateTextAndTitleAsync(database, randomResult);
                SavedTextId = randomResult;
            }
        }
    }
}

RsseRazorPages/Pages/AddText.cshtml
@page
@model RandomSongSearchEngine.Pages.AddTextModel
@{

}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<form method="post">

    <div class="text-center">
        <h1 class="display-4" onclick="hideMenu()">Добавить</h1>
        <textarea name="TitleFromHtml" cols="50" rows="1" wrap="hard">
        @if (@Model.MessageTitle != null)
        {
            foreach (var a in Model.MessageTitle)
            {
                @a
            }
        }
        </textarea>
        <h5>
            <textarea name="TextFromHtml" cols="60" rows="30" wrap="hard">
@if (@Model.Message != null)
{
    foreach (var a in Model.Message)
    {
        @a
    }
}
</textarea>
        </h5>

    </div>

    <div class="layer1">
        <p></p>
        <div id="btns">
            @for (var i = 1; i <= Model.GenresCount; i++)
            {

                <label class="checkbox-btn">
                    <input type="checkbox" name="AreChecked" value="@i" @Model.GenresChecked[i - 1]>
                    <span>@Model.GenresNames[i - 1]</span>
                </label>

            }
            <button class="btn btn-info">Сохранить</button>
        </div>
    </div>
</form>

RsseRazorPages/Pages/Catalog.cshtml
@page
@model RandomSongSearchEngine.Pages.CatalogModel
@{
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="row">
    <p style="margin-left: 12%">Всего песен: @Model.SongsCount &nbsp; Страница: @Model.PageNumber &nbsp; </p>
    <p></p>

    <p></p>
    <table class="table">
        <thead class="thead-dark ">
            <tr>
                <th width="10%"></th>
                <th width="80%">
                    <form method="post">
                        <button name="NavigationButtons" value="1" class="btn btn-info" asp-route-id=@Model.PageNumber>&lt;Назад</button>
                        <button name="NavigationButtons" value="2" class="btn btn-info" asp-route-id=@Model.PageNumber>Вперёд&gt;</button>
                    </form>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var a in Model.TitleAndTextID)
            {
                <tr class="d-sm-table-row "><td></td><td><a asp-page-handler="redirect" asp-route-id=@a.Item2>@a.Item1</a></td></tr>
            }

        </tbody>
    </table>
</div>

RsseRazorPages/Pages/ChangeText.cshtml
@page
@model ChangeTextModel
@{

}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<form method="post">

    <div class="text-center">
        <h1 class="display-4" onclick="hideMenu()">Поменять</h1>
        <textarea name="TitleFromHtml" cols="50" rows="1" wrap="hard">
        @if (@Model.MessageTitle != null)
        {
            foreach (var a in Model.MessageTitle)
            {
                @a
            }
        }
        </textarea>

        <h5>
            <textarea name="TextFromHtml" cols="60" rows="30" wrap="hard">
@if (@Model.Message != null)
{
    foreach (var a in Model.Message)
    {
        @a
    }
}
</textarea>
        </h5>
    </div>

    <div class="layer1">
        <p></p>
        <div id="btns">
            @for (var i = 1; i <= Model.GenresCount; i++)
            {
                <label class="checkbox-btn">
                    <input type="checkbox" name="AreChecked" value="@i" @Model.GenresChecked[i - 1]>
                    <span>@Model.GenresNames[i - 1]</span>
                </label>
            }
            <button class="btn btn-info" asp-route-checkboxes=@Model.InitialCheckboxesAndTextId>Изменить</button>
        </div>
    </div>
</form>

RsseRazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="text-center">
    <h1 class="display-4" onclick="hideMenu()">Рандом</h1>
    <p>
        @if (@Model.MessageTitle != null)
        {
            foreach (var a in Model.MessageTitle)
            {
                @a
            }
        }
    </p>
    <h5>
        <textarea cols="60" rows="30">
        @*<pre>*@
@if (@Model.Message != null)
{
    foreach (var a in Model.Message)
    {
        @a
    }
}
    @*</pre>*@
    </textarea>
    </h5>
</div>

<form method="post">
    <div class="layer1">
        <p></p>
        <div id="btns">
            <p style="color: red; text-align: center;">
                <label class="checkbox-btn">
                    <input type="checkbox" onclick="moreDetailed()" id="flipflop" unchecked />
                    <span style="line-height: 30px;">Все песни</span>
                </label>
                <input class="ib" style="color: red; line-height: 50px; text-align: center;" type="submit" value="=Ищем песню=" />
            </p>
            @for (var i = 1; i <= Model.GenresCount; i++)
            {
                <label class="checkbox-btn">
                    <input type="checkbox" name="AreChecked" value="@i" @Model.GenresChecked[i - 1]>
                    <span style="line-height: 30px;">@Model.GenresNames[i - 1]</span>
                </label>
            }

        </div>
    </div>
</form>